version: '3.9'

services:
  python_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./app:/app"
  envoy:
    build:
      context: .
      dockerfile: ./Dockerfile_Envoy
    ports:
      - 9901:9901
      - 8080:8080
    volumes:
      - "./envoy/envoy.yml:/etc/envoy/envoy.yaml"